# Generated by Django 3.1.1 on 2020-09-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200910_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_advance',
            field=models.FloatField(default=0),
        ),
    ]
