# Generated by Django 3.1.1 on 2020-09-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=1000)),
                ('book_description', models.CharField(max_length=5000)),
                ('book_image', models.ImageField(blank=True, upload_to='books/')),
                ('book_price', models.FloatField()),
                ('book_category', models.CharField(max_length=500)),
            ],
        ),
    ]
