# Generated by Django 3.1.1 on 2020-09-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='rental',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
