# Generated by Django 3.1.1 on 2020-10-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200915_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=1000)),
                ('email', models.CharField(default=0, max_length=1000)),
                ('mobile', models.CharField(default=0, max_length=1000)),
                ('bookname', models.CharField(default=0, max_length=1000)),
                ('bookpublisher', models.CharField(default=0, max_length=1000)),
                ('book_image', models.ImageField(blank=True, upload_to='uploads/')),
            ],
        ),
    ]
