# Generated by Django 3.1.1 on 2020-12-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='deductible',
        ),
    ]
