# Generated by Django 3.1.1 on 2020-12-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_orders_deductible'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='deductible',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
