# Generated by Django 3.1.1 on 2020-12-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_orders_deductible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default=0, max_length=1000)),
                ('book_author', models.CharField(default=0, max_length=1000)),
            ],
        ),
    ]
